<?php
declare(strict_types=1);
require_once __DIR__ . '/config/bootstrap.php';

$page = trim((string)($_GET['page'] ?? 'home'), '/');
if ($page === 'admin/logout') { session_destroy(); redirect('home'); }
if ($page === 'admin/login' && $_SERVER['REQUEST_METHOD'] === 'POST') {
    verify_csrf();
    $username = trim((string)($_POST['username'] ?? ''));
    $password = (string)($_POST['password'] ?? '');
    $account = query_one('SELECT * FROM users WHERE username = ? AND is_active = 1 LIMIT 1', [$username]);
    if ($account && password_verify($password, $account['password_hash'])) { session_regenerate_id(true); $_SESSION['user'] = ['id' => $account['id'], 'username' => $account['username'], 'role' => $account['role']]; redirect('admin'); }
    flash('The credentials did not match.', 'error'); redirect('admin/login');
}
if ($page === 'prospect' && $_SERVER['REQUEST_METHOD'] === 'POST') {
    verify_csrf();
    $name = trim((string)($_POST['full_name'] ?? '')); $phone = trim((string)($_POST['phone_number'] ?? '')); $bike = trim((string)($_POST['bike_model'] ?? ''));
    if ($name === '' || strlen($name) > 100 || $phone === '' || strlen($phone) > 30 || $bike === '') { flash('Name, phone, and bike are required.', 'error'); redirect('prospect'); }
    query_exec('INSERT INTO prospects (full_name, nickname, phone_number, bike_model, reason_to_join) VALUES (?, ?, ?, ?, ?)', [$name, trim((string)($_POST['nickname'] ?? '')), $phone, $bike, trim((string)($_POST['reason_to_join'] ?? ''))]);
    flash('Your note is in. We will be in touch.', 'success'); redirect('prospect');
}
if (str_starts_with($page, 'admin') && $page !== 'admin/login') require_admin();
if ($page === 'admin' && $_SERVER['REQUEST_METHOD'] === 'POST') {
    verify_csrf(); $type = $_POST['entity'] ?? ''; $id = (int)($_POST['id'] ?? 0);
    $allowed = ['events', 'gallery', 'officers', 'merchandise', 'prospects', 'users'];
    if (!in_array($type, $allowed, true)) { flash('Unknown admin action.', 'error'); redirect('admin'); }
    if (($_POST['action'] ?? '') === 'delete' && $id > 0 && $type !== 'users') { query_exec("DELETE FROM {$type} WHERE id = ?", [$id]); flash('Record removed.', 'success'); redirect('admin', ['tab' => $type]); }
    if (($_POST['action'] ?? '') === 'status' && $id > 0 && $type === 'prospects') { query_exec('UPDATE prospects SET status = ? WHERE id = ?', [$_POST['status'] ?? 'reviewed', $id]); flash('Prospect status updated.', 'success'); redirect('admin', ['tab' => 'prospects']); }
    if (($_POST['action'] ?? '') === 'save') {
        if ($type === 'events') { $values = [trim($_POST['title'] ?? ''), $_POST['event_date'] ?? '', trim($_POST['location'] ?? ''), trim($_POST['description'] ?? ''), $_POST['status'] ?? 'upcoming']; $id ? query_exec('UPDATE events SET title=?, event_date=?, location=?, description=?, status=? WHERE id=?', [...$values, $id]) : query_exec('INSERT INTO events (title,event_date,location,description,status) VALUES (?,?,?,?,?)', $values); }
        if ($type === 'gallery') { $image = upload_image('image', 'gallery'); $values = [trim($_POST['title'] ?? ''), $image ?: ($_POST['image_path'] ?? ''), $_POST['category'] ?? 'touring']; $id ? query_exec('UPDATE gallery SET title=?, image_path=?, category=? WHERE id=?', [...$values, $id]) : query_exec('INSERT INTO gallery (title,image_path,category) VALUES (?,?,?)', $values); }
        if ($type === 'officers') { $image = upload_image('image', 'officers'); $values = [trim($_POST['name'] ?? ''), trim($_POST['position'] ?? ''), trim($_POST['bio'] ?? ''), $image ?: trim($_POST['image_path'] ?? '')]; $id ? query_exec('UPDATE officers SET name=?, position=?, bio=?, image_path=? WHERE id=?', [...$values, $id]) : query_exec('INSERT INTO officers (name,position,bio,image_path) VALUES (?,?,?,?)', $values); }
        if ($type === 'merchandise') { $image = upload_image('image', 'merchandise'); $values = [trim($_POST['name'] ?? ''), trim($_POST['description'] ?? ''), (float)($_POST['price'] ?? 0), $image ?: trim($_POST['image_path'] ?? ''), (int)($_POST['stock'] ?? 0)]; $id ? query_exec('UPDATE merchandise SET name=?, description=?, price=?, image_path=?, stock=? WHERE id=?', [...$values, $id]) : query_exec('INSERT INTO merchandise (name,description,price,image_path,stock) VALUES (?,?,?,?,?)', $values); }
        flash('Changes saved.', 'success'); redirect('admin', ['tab' => $type]);
    }
}

$publicPages = ['home', 'about', 'gallery', 'events', 'event', 'shop', 'prospect', 'contact'];
if ($page === 'admin/login') { $title = 'Member access | Mischief Outlaws'; require __DIR__ . '/includes/header.php'; ?>
<section class="auth-page"><div class="auth-panel"><p class="eyebrow">Private road</p><h1>Member access</h1><p class="muted">For officers and crew with a key to the clubhouse.</p><form method="post"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><label>Username<input name="username" required autocomplete="username"></label><label>Password<input type="password" name="password" required autocomplete="current-password"></label><button class="button button-red" type="submit">Enter</button></form></div></section>
<?php require __DIR__ . '/includes/footer.php'; exit; }
if (!in_array($page, $publicPages, true) && $page !== 'admin') { http_response_code(404); $page = 'home'; }
$title = match ($page) { 'home' => 'Mischief Outlaws MC', 'about' => 'The Charter | Mischief Outlaws', 'gallery' => 'Garage Archive | Mischief Outlaws', 'events', 'event' => 'Rides & Events | Mischief Outlaws', 'shop' => 'Goods | Mischief Outlaws', 'prospect' => 'Make Contact | Mischief Outlaws', 'contact' => 'Contact | Mischief Outlaws', 'admin' => 'Dashboard | Mischief Outlaws', default => 'Mischief Outlaws MC' };
require __DIR__ . '/includes/header.php';
if ($page === 'home'): $events = query_all('SELECT * FROM events WHERE event_date >= CURDATE() ORDER BY event_date ASC LIMIT 3'); if (!$events) $events = demo_records('events'); ?>
<section class="hero"><div class="hero-image"></div><div class="shell hero-content"><p class="eyebrow">Mischief Outlaws Motorcycle Club</p><h1>Keep the machine<br><em>honest.</em></h1><p class="hero-copy">A riding club built around the road, the garage, and the people who show up when it matters.</p><a class="button button-red" href="<?= url('prospect') ?>">Start a conversation <span>↗</span></a></div><div class="hero-stamp">Est. on the road<br><b>MO / MC</b></div></section>
<section class="shell intro-grid"><div><p class="eyebrow">The charter</p><h2>No spectators.<br><span>Just riders.</span></h2></div><div class="prose"><p>We keep our circle deliberate and our standards plain. The work happens in the garage, the miles make the bond, and every new face gets met person to person.</p><a class="text-link" href="<?= url('about') ?>">Read the charter <span>→</span></a></div></section>
<section class="image-band"><div class="shell image-band-copy"><p class="eyebrow">From the garage</p><h2>Steel, weather,<br>and a little noise.</h2><a class="button button-ghost" href="<?= url('gallery') ?>">Open the archive</a></div></section>
<section class="shell events-preview"><div class="section-head"><div><p class="eyebrow">On the calendar</p><h2>Next miles</h2></div><a class="text-link" href="<?= url('events') ?>">All rides <span>→</span></a></div><?php if (!$events): ?><p class="empty">The calendar is quiet for now. Check back soon.</p><?php else: foreach ($events as $event): ?><a class="event-row" href="<?= url('event', ['id' => $event['id']]) ?>"><time datetime="<?= e($event['event_date']) ?>"><b><?= date('d', strtotime($event['event_date'])) ?></b><?= date('M', strtotime($event['event_date'])) ?></time><span><strong><?= e($event['title']) ?></strong><small><?= e($event['location']) ?></small><span class="event-thumb" style="background-image:url('<?= e(image_url($event['image_path'], demo_image('events', (int)$event['id']))) ?>')" role="img" aria-label="Demo image for <?= e($event['title']) ?>"></span></span><span class="arrow">↗</span></a><?php endforeach; endif; ?></section>
<?php elseif ($page === 'about'): $officers = query_all('SELECT * FROM officers ORDER BY sort_order, id'); if (!$officers) $officers = demo_records('officers'); ?>
<section class="page-hero shell"><p class="eyebrow">The charter</p><h1>Keep it real.<br><em>Keep it moving.</em></h1><p class="lede">A few principles carry more weight than a long speech.</p></section><section class="shell charter-grid"><div class="charter-list"><article><span>01</span><h2>Show up.</h2><p>The road is a shared responsibility. Be present, be prepared, and look after the rider beside you.</p></article><article><span>02</span><h2>Earn trust.</h2><p>Names and patches mean less than how you conduct yourself when nobody is keeping score.</p></article><article><span>03</span><h2>Leave it better.</h2><p>Respect the machine, the places we pass through, and the people who make the miles possible.</p></article></div><aside class="charter-note"><p class="eyebrow">Clubhouse note</p><p>Membership starts with a conversation. There is no online shortcut around getting to know one another.</p></aside></section><section class="shell officers"><div class="section-head"><div><p class="eyebrow">The people who keep it rolling</p><h2>Charter hierarchy</h2></div><p class="hierarchy-key">Chain of command · Mischief Outlaws MC</p></div>
<?php
$president = array_values(array_filter($officers, static fn(array $officer): bool => strcasecmp($officer['position'], 'President') === 0));
$vice = array_values(array_filter($officers, static fn(array $officer): bool => strcasecmp($officer['position'], 'Vice') === 0));
$security = array_values(array_filter($officers, static fn(array $officer): bool => in_array(strtolower($officer['position']), ['sergeant at arms', 'enforcer'], true)));
$administration = array_values(array_filter($officers, static fn(array $officer): bool => strcasecmp($officer['position'], 'Treasurer') === 0));
$roadOperations = array_values(array_filter($officers, static fn(array $officer): bool => strcasecmp($officer['position'], 'Road Captain') === 0));
$renderOfficer = static function (array $officer, string $class = ''): void { ?>
<article class="officer tree-card <?= e($class) ?>"><div class="officer-image" style="background-image:url('<?= e(image_url($officer['image_path'], demo_image('officers', (int)$officer['id']))) ?>')"></div><div class="officer-copy"><p class="eyebrow"><?= e($officer['position']) ?></p><h3><?= e($officer['name']) ?></h3><p class="muted"><?= e($officer['bio']) ?></p></div></article>
<?php }; ?>
<div class="mc-tree" aria-label="Mischief Outlaws MC charter hierarchy">
  <div class="mc-tree-level mc-tree-president"><?php foreach ($president as $officer) $renderOfficer($officer, 'tree-card-primary'); ?></div>
  <div class="mc-tree-level mc-tree-vice"><?php foreach ($vice as $officer) $renderOfficer($officer, 'tree-card-secondary'); ?></div>
  <div class="mc-tree-branches">
    <section class="mc-branch"><header><span>01</span><div><p>Security</p><small>Order & charter standards</small></div></header><div class="mc-branch-members"><?php foreach ($security as $officer) $renderOfficer($officer); ?></div></section>
    <section class="mc-branch"><header><span>02</span><div><p>Administration</p><small>Records & treasury</small></div></header><div class="mc-branch-members"><?php foreach ($administration as $officer) $renderOfficer($officer); ?></div></section>
    <section class="mc-branch"><header><span>03</span><div><p>Road operations</p><small>Routes & ride formation</small></div></header><div class="mc-branch-members"><?php foreach ($roadOperations as $officer) $renderOfficer($officer); ?></div></section>
  </div>
</div></section>
<?php elseif ($page === 'gallery'): $category = $_GET['category'] ?? ''; $gallery = query_all('SELECT * FROM gallery ' . ($category ? 'WHERE category = ? ' : '') . 'ORDER BY created_at DESC', $category ? [$category] : []); if (!$gallery) { $gallery = demo_records('gallery'); if ($category) $gallery = array_values(array_filter($gallery, static fn(array $item): bool => $item['category'] === $category)); } ?>
<section class="page-hero shell"><p class="eyebrow">Garage archive</p><h1>Made of miles<br><em>and maintenance.</em></h1><div class="filters"><a class="<?= !$category ? 'active' : '' ?>" href="<?= url('gallery') ?>">All</a><?php foreach (['touring','clubhouse','bikes','events'] as $filter): ?><a class="<?= $category === $filter ? 'active' : '' ?>" href="<?= url('gallery', ['category' => $filter]) ?>"><?= ucfirst($filter) ?></a><?php endforeach; ?></div></section><section class="shell gallery-grid"><?php foreach ($gallery as $item): $itemImage = image_url($item['image_path'], demo_image('gallery', (int)$item['id'])); ?><button class="gallery-item" data-lightbox data-src="<?= e($itemImage) ?>" data-alt="<?= e($item['title']) ?>"><img src="<?= e($itemImage) ?>" alt="<?= e($item['title']) ?>" loading="lazy"><span><?= e($item['title']) ?></span></button><?php endforeach; ?><?php if (!$gallery): ?><p class="empty">No photographs in this part of the archive yet.</p><?php endif; ?></section><dialog id="lightbox"><button data-close aria-label="Close image">×</button><img src="" alt=""></dialog>
<?php elseif ($page === 'events' || $page === 'event'): $selected = $page === 'event' ? query_one('SELECT * FROM events WHERE id = ?', [(int)($_GET['id'] ?? 0)]) : null; $events = query_all('SELECT * FROM events ORDER BY event_date DESC'); if (!$events) $events = demo_records('events'); if ($page === 'event' && !$selected) { $requestedId = (int)($_GET['id'] ?? 0); foreach ($events as $eventRecord) { if ((int)$eventRecord['id'] === $requestedId) { $selected = $eventRecord; break; } } if (!$selected) http_response_code(404); } ?>
<?php if ($selected): ?><section class="shell detail"><p class="eyebrow">Ride detail · <?= e(format_date($selected['event_date'])) ?></p><h1><?= e($selected['title']) ?></h1><p class="lede"><?= e($selected['location']) ?></p><div class="event-detail-image" style="background-image:url('<?= e(image_url($selected['image_path'], demo_image('events', (int)$selected['id']))) ?>')" role="img" aria-label="Demo event photograph"></div><div class="detail-body"><p><?= nl2br(e($selected['description'])) ?></p><a class="button button-red" href="<?= url('prospect') ?>">Ask about this ride</a></div></section><?php else: ?><section class="page-hero shell"><p class="eyebrow">The calendar</p><h1>Next miles.<br><em>Worth taking.</em></h1></section><section class="shell event-list"><?php foreach ($events as $event): ?><a class="event-row" href="<?= url('event', ['id' => $event['id']]) ?>"><time datetime="<?= e($event['event_date']) ?>"><b><?= date('d', strtotime($event['event_date'])) ?></b><?= date('M', strtotime($event['event_date'])) ?></time><span><strong><?= e($event['title']) ?></strong><small><?= e($event['location']) ?></small><span class="event-thumb" style="background-image:url('<?= e(image_url($event['image_path'], demo_image('events', (int)$event['id']))) ?>')" role="img" aria-label="Demo image for <?= e($event['title']) ?>"></span></span><span class="event-desc"><?= e($event['description']) ?></span><span class="arrow">↗</span></a><?php endforeach; ?><?php if (!$events): ?><p class="empty">No rides have been posted yet.</p><?php endif; ?></section><?php endif; ?>
<?php elseif ($page === 'shop'): $items = query_all('SELECT * FROM merchandise WHERE active = 1 ORDER BY id DESC'); if (!$items) $items = demo_records('merchandise'); ?><section class="page-hero shell"><p class="eyebrow">Club goods</p><h1>Useful things.<br><em>No souvenirs.</em></h1><p class="lede">Small runs for people who know the difference between a patch and a costume.</p></section><section class="shell product-grid"><?php foreach ($items as $item): $itemImage = image_url($item['image_path'], demo_image('merchandise', (int)$item['id'])); ?><article class="product"><div class="product-image" style="background-image:url('<?= e($itemImage) ?>')" role="img" aria-label="<?= e($item['name']) ?>"></div><div class="product-meta"><h2><?= e($item['name']) ?></h2><p class="muted"><?= e($item['description']) ?></p><strong>$<?= number_format((float)$item['price'], 2) ?></strong><a class="text-link" href="<?= url('contact') ?>">Ask about stock →</a></div></article><?php endforeach; ?><?php if (!$items): ?><p class="empty">The shelves are being restocked. Check back soon.</p><?php endif; ?></section>
<?php elseif ($page === 'prospect'): ?><section class="page-hero shell"><p class="eyebrow">Make contact</p><h1>Start with a<br><em>conversation.</em></h1><p class="lede">Tell us a little about yourself. No performance required.</p></section><section class="shell form-layout"><form class="form-panel" method="post"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><div class="form-row"><label>Name *<input name="full_name" required maxlength="100" value="<?= old('full_name') ?>"></label><label>Nickname<input name="nickname" maxlength="50" value="<?= old('nickname') ?>"></label></div><div class="form-row"><label>Phone *<input name="phone_number" required maxlength="30" value="<?= old('phone_number') ?>"></label><label>Bike *<input name="bike_model" required maxlength="100" value="<?= old('bike_model') ?>"></label></div><label>Why ride with us?<textarea name="reason_to_join" rows="5" maxlength="2000"><?= old('reason_to_join') ?></textarea></label><button class="button button-red" type="submit">Send the note <span>↗</span></button></form><aside class="form-aside"><p class="eyebrow">A word about process</p><p>We read every message. If there is a fit, one of the officers will reach out privately with next steps.</p></aside></section>
<?php elseif ($page === 'contact'): ?><section class="page-hero shell"><p class="eyebrow">Contact</p><h1>Come by the<br><em>long way around.</em></h1></section><section class="shell contact-grid"><div><p class="eyebrow">Clubhouse</p><h2>Location shared<br>with prospects.</h2></div><div class="prose"><p>For general questions, use the prospect form or send a note through the channels where you found us. We keep the clubhouse quiet by design.</p><a class="button button-red" href="<?= url('prospect') ?>">Make contact</a></div></section>
<?php elseif ($page === 'admin'): $tab = $_GET['tab'] ?? 'overview'; $counts = []; foreach (['events','gallery','officers','merchandise','prospects','users'] as $table) { $row = query_one("SELECT COUNT(*) AS total FROM {$table}"); $counts[$table] = (int)($row['total'] ?? 0); } ?>
<section class="admin-shell shell"><div class="admin-head"><div><p class="eyebrow">Private road</p><h1>Dashboard</h1></div><a class="text-link" href="<?= url('admin/logout') ?>">Log out ↗</a></div><nav class="admin-tabs"><?php foreach (['overview','events','gallery','officers','merchandise','prospects'] as $item): ?><a class="<?= $tab === $item ? 'active' : '' ?>" href="<?= url('admin', ['tab' => $item]) ?>"><?= ucfirst($item) ?></a><?php endforeach; ?></nav>
<?php if ($tab === 'overview'): ?><div class="admin-stats"><?php foreach (['events','gallery','officers','merchandise','prospects'] as $item): ?><a href="<?= url('admin', ['tab' => $item]) ?>"><span><?= $counts[$item] ?></span><?= ucfirst($item) ?></a><?php endforeach; ?></div><div class="admin-note"><p class="eyebrow">Good evening, <?= e($user['username']) ?></p><p>Use the sections above to keep the public calendar, garage archive, roster, and goods current.</p></div>
<?php elseif ($tab === 'prospects'): $rows = query_all('SELECT * FROM prospects ORDER BY created_at DESC'); ?><div class="admin-table"><h2>Prospects</h2><?php foreach ($rows as $row): ?><div class="admin-row"><span><strong><?= e($row['full_name']) ?></strong><small><?= e($row['bike_model']) ?> · <?= e($row['phone_number']) ?></small></span><form method="post"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="entity" value="prospects"><input type="hidden" name="id" value="<?= $row['id'] ?>"><input type="hidden" name="action" value="status"><select name="status" onchange="this.form.submit()"><?php foreach (['pending','reviewed','accepted','rejected'] as $status): ?><option <?= $row['status'] === $status ? 'selected' : '' ?>><?= $status ?></option><?php endforeach; ?></select></form></div><?php endforeach; ?><?php if (!$rows): ?><p class="empty">No prospect notes yet.</p><?php endif; ?></div>
<?php else: $rows = query_all("SELECT * FROM {$tab} ORDER BY id DESC"); ?><div class="admin-table"><div class="admin-table-head"><h2><?= ucfirst($tab) ?></h2><button class="button button-red" type="button" onclick="document.querySelector('#new-record').hidden=false">New record</button></div><form id="new-record" class="admin-form" method="post" enctype="multipart/form-data" hidden><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="entity" value="<?= e($tab) ?>"><input type="hidden" name="action" value="save"><?php if ($tab === 'events'): ?><input name="title" placeholder="Title" required><input name="event_date" type="date" required><input name="location" placeholder="Location" required><textarea name="description" placeholder="Description" required></textarea><select name="status"><option>upcoming</option><option>completed</option></select><?php elseif ($tab === 'gallery'): ?><input name="title" placeholder="Title" required><input name="image" type="file" accept="image/jpeg,image/png,image/webp"><input name="image_path" placeholder="Image URL fallback"><select name="category"><option>touring</option><option>clubhouse</option><option>bikes</option><option>events</option></select><?php elseif ($tab === 'officers'): ?><input name="name" placeholder="Name" required><input name="position" placeholder="Position" required><textarea name="bio" placeholder="Bio" required></textarea><input name="image_path" placeholder="Image URL"><?php elseif ($tab === 'merchandise'): ?><input name="name" placeholder="Name" required><textarea name="description" placeholder="Description" required></textarea><input name="price" type="number" step="0.01" placeholder="Price"><input name="stock" type="number" placeholder="Stock"><input name="image_path" placeholder="Image URL"><?php endif; ?><button class="button button-red" type="submit">Save</button></form><?php foreach ($rows as $row): ?><div class="admin-row"><span><strong><?= e($row['title'] ?? $row['name']) ?></strong><small><?= e($row['location'] ?? $row['position'] ?? $row['category'] ?? '$' . number_format((float)($row['price'] ?? 0), 2)) ?></small></span><form method="post" data-confirm="Remove this record?"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="entity" value="<?= e($tab) ?>"><input type="hidden" name="id" value="<?= $row['id'] ?>"><input type="hidden" name="action" value="delete"><button class="delete" type="submit">Delete</button></form></div><?php endforeach; ?></div><?php endif; ?></section>
<?php endif;
require __DIR__ . '/includes/footer.php';
